#!/usr/bin/env node
// Zero-dependency generator for the repo-level library catalog
// (`docs/CATALOG.md`).
//
// The catalog is a projection of what is actually on disk: it discovers every
// `src/<module>/package.json` (top-level dirs only, mirroring the discovery in
// `scripts/test-all.mjs`) and renders a deterministic Markdown table from each
// module's `name` / `description` / `main` / `test` script. Because the file is
// generated, it can never silently drift from the modules — the `--check` mode
// is wired into CI to fail any PR whose committed `docs/CATALOG.md` differs from
// a fresh render.
//
// This is the docs-level, root-README-linked catalog. It complements
// `src/README.md` (the in-src toolbox landing page, generated by
// `scripts/gen-toolbox-readme.mjs`) by adding a per-module TEST COMMAND column
// and living under `docs/` for top-level discoverability.
//
// Modes:
//   (no args)   WRITE  — render and overwrite `docs/CATALOG.md`.
//   --check     VERIFY — render in memory, diff against the committed file, and
//                        exit 1 (with a fix hint) when they differ; exit 0 when
//                        they match. This is the drift gate.
//
// Uses Node built-ins only — no runtime dependencies.

import { readdirSync, existsSync, readFileSync, writeFileSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(repoRoot, 'src');
const catalogPath = join(repoRoot, 'docs', 'CATALOG.md');

const BANNER =
  '<!-- AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand; run `node scripts/gen-catalog.mjs` -->';

// Discover top-level `src/<module>/` dirs that carry a `package.json`, exactly
// as `scripts/test-all.mjs` and `scripts/gen-toolbox-readme.mjs` do (README.md
// and non-dir entries fall away). Sorted alphabetically for deterministic
// output.
function discoverModules() {
  if (!existsSync(srcDir)) return [];
  return readdirSync(srcDir)
    .map((name) => ({ name, dir: join(srcDir, name) }))
    .filter(({ dir }) => {
      try {
        return statSync(dir).isDirectory();
      } catch {
        return false;
      }
    })
    .filter(({ dir }) => existsSync(join(dir, 'package.json')))
    .map(({ name, dir }) => ({
      name,
      pkg: JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

// The module's entry path relative to the repo root, e.g. `src/retry/retry.ts`.
// `main` may carry a leading `./` (Node allows it); strip it so the rendered
// path is clean. Fall back to `index.js` — Node's default — when `main` is
// absent.
function entryPath(name, pkg) {
  const main = (pkg.main ?? 'index.js').replace(/^\.\//, '');
  return `src/${name}/${main}`;
}

// The command that runs this module's own tests from the repo root. Every
// testable module declares a `test` script and is run by its OWN runner via
// `npm test` (see scripts/test-all.mjs); `--prefix` points npm at the module
// dir without a `cd`. Modules with no `test` script render an em-dash.
function testCommand(name, pkg) {
  const hasTest = pkg.scripts && typeof pkg.scripts.test === 'string';
  return hasTest ? `npm test --prefix src/${name}` : '—';
}

// Escape the Markdown table-cell delimiter so a `|` inside a description cannot
// break the table. Descriptions are otherwise rendered verbatim (the full
// description, not just the first sentence — this catalog is the fuller view).
function cell(text) {
  return (text ?? '').replace(/\|/g, '\\|').trim();
}

function renderTable(modules) {
  const header = ['| Module | Description | Entry | Test command |', '|---|---|---|---|'];
  const rows = modules.map(({ name, pkg }) => {
    const desc = cell(pkg.description) || '(no description)';
    const entry = `\`${entryPath(name, pkg)}\``;
    const test = `\`${testCommand(name, pkg)}\``;
    return `| [${name}](../src/${name}/) | ${desc} | ${entry} | ${test} |`;
  });
  return [...header, ...rows].join('\n');
}

function render(modules) {
  return `${BANNER}

# Library catalog

An index of every zero-dependency utility library under [\`src/\`](../src/). Each
module is pure, dependency-free (no runtime \`node_modules\` required to import
it), and independently tested under its own declared runner.

This catalog is **generated** from each module's \`package.json\` — do not edit it
by hand. Run \`node scripts/gen-catalog.mjs\` to regenerate it. CI runs
\`node scripts/gen-catalog.mjs --check\` and fails any change where the committed
file has drifted from a fresh render, so adding, renaming, or re-describing a
library that forgets to update this catalog cannot reach \`alpha\`.

For the in-\`src/\` toolbox landing page (with a slightly different view of the
same modules) see [\`src/README.md\`](../src/README.md).

## Modules

${renderTable(modules)}

## How this stays fresh

- Each row is derived from \`src/<module>/package.json\` (\`name\`, \`description\`,
  \`main\`, and the \`test\` script). There is no hand-maintained list to fall out
  of date.
- **Test command** runs a single module's suite from the repo root; run the
  whole suite with \`node scripts/test-all.mjs\` (or \`npm test\`).
- The CI drift guard (\`scripts/gen-catalog.mjs --check\`) is the enforcement: a
  stale catalog fails the build.
`;
}

function main() {
  const check = process.argv.includes('--check');
  const modules = discoverModules();
  const rendered = render(modules);

  if (!check) {
    mkdirSync(dirname(catalogPath), { recursive: true });
    writeFileSync(catalogPath, rendered);
    console.log(`Wrote ${modules.length} module(s) to docs/CATALOG.md`);
    return;
  }

  const committed = existsSync(catalogPath) ? readFileSync(catalogPath, 'utf8') : '';
  if (committed === rendered) {
    console.log('docs/CATALOG.md is up to date.');
    process.exit(0);
  }

  console.error('docs/CATALOG.md is stale — run `node scripts/gen-catalog.mjs` to regenerate it.');
  // Point at the first differing line to make the drift concrete.
  const a = committed.split('\n');
  const b = rendered.split('\n');
  const max = Math.max(a.length, b.length);
  for (let i = 0; i < max; i++) {
    if (a[i] !== b[i]) {
      console.error(`  first diff at line ${i + 1}:`);
      console.error(`    committed: ${a[i] ?? '(end of file)'}`);
      console.error(`    expected:  ${b[i] ?? '(end of file)'}`);
      break;
    }
  }
  process.exit(1);
}

main();
